# Generated by Django 5.2 on 2025-04-04 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_immobiliere_yesoda', '0002_remove_bien_code_postal_remove_bien_ville_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technicien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('specialite', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
                ('duree_estimee', models.DurationField(help_text='Durée estimée (hh:mm:ss)')),
                ('marge_prevue', models.DurationField(default='01:30:00', help_text='Marge pour imprévus (hh:mm:ss)')),
                ('evaluation', models.PositiveSmallIntegerField(blank=True, help_text='Note donnée par le locataire (1-5)', null=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_immobiliere_yesoda.bien')),
                ('technicien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_immobiliere_yesoda.technicien')),
            ],
        ),
    ]
