# Generated by Django 5.2 on 2025-04-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_immobiliere_yesoda', '0003_technicien_intervention'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('budget_utilise', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='locataire',
            name='points_fidelite',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
