# Generated by Django 5.2 on 2025-04-09 10:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_immobiliere_yesoda', '0004_missionjour_locataire_points_fidelite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MissionJour',
        ),
        migrations.AlterModelOptions(
            name='bien',
            options={'verbose_name': 'Bien', 'verbose_name_plural': 'Biens'},
        ),
        migrations.AlterModelOptions(
            name='intervention',
            options={'verbose_name': 'Intervention', 'verbose_name_plural': 'Interventions'},
        ),
        migrations.AlterModelOptions(
            name='locataire',
            options={'verbose_name': 'Locataire', 'verbose_name_plural': 'Locataires'},
        ),
        migrations.AlterModelOptions(
            name='proprietaire',
            options={'verbose_name': 'Propriétaire', 'verbose_name_plural': 'Propriétaires'},
        ),
        migrations.AlterModelOptions(
            name='technicien',
            options={'verbose_name': 'Technicien', 'verbose_name_plural': 'Techniciens'},
        ),
        migrations.RemoveField(
            model_name='locataire',
            name='points_fidelite',
        ),
        migrations.AddField(
            model_name='bien',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='bien',
            name='est_loue',
            field=models.BooleanField(default=False, verbose_name='Est loué ?'),
        ),
        migrations.AddField(
            model_name='bien',
            name='etage_porte',
            field=models.CharField(blank=True, max_length=50, verbose_name='Étage et porte'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='adresse',
            field=models.CharField(max_length=255, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='compteur_eau',
            field=models.IntegerField(default=0, verbose_name="Compteur d'eau"),
        ),
        migrations.AlterField(
            model_name='bien',
            name='compteur_electricite',
            field=models.IntegerField(default=0, verbose_name="Compteur d'électricité"),
        ),
        migrations.AlterField(
            model_name='bien',
            name='compteur_gaz',
            field=models.IntegerField(default=0, verbose_name='Compteur de gaz'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='contrat_pdf',
            field=models.FileField(blank=True, null=True, upload_to='contrats/', verbose_name='Contrat PDF'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='etat_lieux_entree',
            field=models.TextField(blank=True, verbose_name="État des lieux d'entrée"),
        ),
        migrations.AlterField(
            model_name='bien',
            name='etat_lieux_sortie',
            field=models.TextField(blank=True, verbose_name='État des lieux de sortie'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='locataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_immobiliere_yesoda.locataire', verbose_name='Locataire'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='loyer',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Loyer mensuel (€)'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_immobiliere_yesoda.proprietaire', verbose_name='Propriétaire'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='surface',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Surface (m²)'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='bien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_immobiliere_yesoda.bien', verbose_name='Bien'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='duree_estimee',
            field=models.DurationField(verbose_name='Durée estimée'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='evaluation',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Évaluation (1-5)'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='marge_prevue',
            field=models.DurationField(default='01:30:00', verbose_name='Marge pour imprévus'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='technicien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_immobiliere_yesoda.technicien', verbose_name='Technicien'),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='date_entree',
            field=models.DateField(verbose_name="Date d'entrée"),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='date_sortie',
            field=models.DateField(blank=True, null=True, verbose_name='Date de sortie'),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='remarques',
            field=models.TextField(blank=True, verbose_name='Remarques'),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='technicien',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='technicien',
            name='specialite',
            field=models.CharField(max_length=100, verbose_name='Spécialité'),
        ),
        migrations.AlterField(
            model_name='technicien',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='Téléphone'),
        ),
    ]
