# Generated by Django 5.2 on 2025-04-09 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_immobiliere_yesoda', '0005_delete_missionjour_alter_bien_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionDuJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description de la mission')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date de la mission')),
                ('statut', models.CharField(choices=[('À faire', 'À faire'), ('Terminé', 'Terminé')], default='À faire', max_length=20, verbose_name='Statut')),
                ('budget_alloue', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Budget alloué')),
                ('remarque', models.TextField(blank=True, verbose_name='Remarque')),
            ],
            options={
                'verbose_name': 'Mission du jour',
                'verbose_name_plural': 'Missions du jour',
            },
        ),
        migrations.AddField(
            model_name='bien',
            name='missions_du_jour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='biens', to='app_immobiliere_yesoda.missiondujour', verbose_name='Missions du jour'),
            preserve_default=False,
        ),
    ]
