# Generated by Django 5.2 on 2025-04-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_immobiliere_yesoda', '0007_alter_bien_options_alter_intervention_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missiondujour',
            name='commentaire',
        ),
        migrations.AddField(
            model_name='missiondujour',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En Cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_cours', max_length=10),
        ),
        migrations.AlterField(
            model_name='missiondujour',
            name='budget_estime',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='missiondujour',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='missiondujour',
            name='taches',
            field=models.TextField(),
        ),
    ]
